#lang rosette

(provide (all-defined-out))

; Independent parameters
(define BLOCKS_DELTA 64)
(define BLOCKS_FULL 1)
(define BLOCKS_DATA 1536)
(define PAGES_PER_BLOCK 512)
(define PAGE_SIZE 8192)
(define SECTOR_SIZE 4096)
(define MAX_WCNT 2048)
(define THRESHOLD_GC 1400)

; Dependent parameters
(define BLOCKS_TOTAL (+ BLOCKS_DELTA (* 2 (+ BLOCKS_FULL 1)) BLOCKS_DATA))
(define N_ENTRIES_PER_PAGE (/ PAGE_SIZE 4))
(define N_ENTRIES_PER_SECTOR (/ SECTOR_SIZE 4))
(define SECTORS_PER_PAGE (/ PAGE_SIZE SECTOR_SIZE))
(define SECTORS_PER_BLOCK (* PAGES_PER_BLOCK SECTORS_PER_PAGE))
(define N_LAS  (- (* BLOCKS_FULL PAGES_PER_BLOCK N_ENTRIES_PER_PAGE) 1))
(define N_PAS (* BLOCKS_TOTAL PAGES_PER_BLOCK SECTORS_PER_PAGE))
(define N_DELTA_PAIR (- (/ N_ENTRIES_PER_PAGE 2) 1))
(define THRESHOLD_DELTA_WB (- BLOCKS_DELTA (+ (floor (/ MAX_WCNT (* N_DELTA_PAIR PAGES_PER_BLOCK))) 2)))
(define MAX_GCPROG (* MAX_WCNT 16))

; Block layout
(define PBA_DELTA_START 0)
(define PBA_DELTA_END  (+ PBA_DELTA_START BLOCKS_DELTA))
(define PBA_FIRST_FULL BLOCKS_DELTA)
(define PBA_FIRST_FULL_COMMIT (+ PBA_FIRST_FULL BLOCKS_FULL))
(define PBA_SECOND_FULL (+ PBA_FIRST_FULL_COMMIT 1))
(define PBA_SECOND_FULL_COMMIT (+ PBA_SECOND_FULL BLOCKS_FULL))
(define PBA_DATA (+ PBA_SECOND_FULL_COMMIT 1))

; Offset for delta chkpt page
(define OFFSET_COMMIT 0)
(define OFFSET_LAS 2)
(define OFFSET_PAS (+ OFFSET_LAS N_DELTA_PAIR))
